namespace OpenInput.RawInput
{
    using System;
    using KeysConverter = System.Windows.Forms.KeysConverter;

    class KeyMapper
    {
        static Lazy<KeysConverter> keysConverter = new Lazy<KeysConverter>();
        
        public static string GetKeyName(int virtualKey)
        {
            return keysConverter.Value.ConvertToString(virtualKey);
        }

        public static Keys ToKeys(int key)
        {
            return Keys.Unknown;
            switch (key)
            {
                //case Keys.Unknown:
                //    break;
                //case Keys.Left:
                //    break;
                //case Keys.Up:
                //    break;
                //case Keys.Right:
                //    break;
                //case Keys.Down:
                //    break;
                //case Keys.Tab:
                //    break;
                //case Keys.Return:
                //    break;
                //case Keys.Enter:
                //    break;
                //case Keys.Escape:
                //    break;
                //case Keys.Space:
                //    break;
                //case Keys.Back:
                //    break;
                //case Keys.BackSpace:
                //    break;
                //case Keys.Insert:
                //    break;
                //case Keys.Delete:
                //    break;
                //case Keys.PageUp:
                //    break;
                //case Keys.PageDown:
                //    break;
                //case Keys.End:
                //    break;
                //case Keys.Home:
                //    break;
                //case Keys.CapsLock:
                //    break;
                //case Keys.Scroll:
                //    break;
                //case Keys.ScrollLock:
                //    break;
                //case Keys.PrintScreen:
                //    break;
                //case Keys.Pause:
                //    break;
                //case Keys.NumLock:
                //    break;
                //case Keys.Sleep:
                //    break;
                //case Keys.LWin:
                //    break;
                //case Keys.RWin:
                //    break;
                //case Keys.Apps:
                //    break;
                //case Keys.LaunchMail:
                //    break;
                //case Keys.SelectMedia:
                //    break;
                //case Keys.LaunchApplication1:
                //    break;
                //case Keys.LaunchApplication2:
                //    break;
                //case Keys.BrowserBack:
                //    break;
                //case Keys.BrowserForward:
                //    break;
                //case Keys.BrowserRefresh:
                //    break;
                //case Keys.BrowserStop:
                //    break;
                //case Keys.BrowserSearch:
                //    break;
                //case Keys.BrowserFavorites:
                //    break;
                //case Keys.BrowserHome:
                //    break;
                //case Keys.VolumeMute:
                //    break;
                //case Keys.VolumeDown:
                //    break;
                //case Keys.VolumeUp:
                //    break;
                //case Keys.MediaNextTrack:
                //    break;
                //case Keys.MediaPreviousTrack:
                //    break;
                //case Keys.MediaStop:
                //    break;
                //case Keys.MediaPlayPause:
                //    break;
                //case Keys.LShiftKey:
                //    break;
                //case Keys.RShiftKey:
                //    break;
                //case Keys.LeftShift:
                //    break;
                //case Keys.RightShift:
                //    break;
                //case Keys.LControlKey:
                //    break;
                //case Keys.RControlKey:
                //    break;
                //case Keys.LeftControl:
                //    break;
                //case Keys.RightControl:
                //    break;
                //case Keys.LAltKey:
                //    break;
                //case Keys.RAltKey:
                //    break;
                //case Keys.LeftAlt:
                //    break;
                //case Keys.RightAlt:
                //    break;
                //case Keys.Menu:
                //    break;
                //case Keys.LMenu:
                //    break;
                //case Keys.RMenu:
                //    break;
                //case Keys.F1:
                //    break;
                //case Keys.F2:
                //    break;
                //case Keys.F3:
                //    break;
                //case Keys.F4:
                //    break;
                //case Keys.F5:
                //    break;
                //case Keys.F6:
                //    break;
                //case Keys.F7:
                //    break;
                //case Keys.F8:
                //    break;
                //case Keys.F9:
                //    break;
                //case Keys.F10:
                //    break;
                //case Keys.F11:
                //    break;
                //case Keys.F12:
                //    break;
                //case Keys.F13:
                //    break;
                //case Keys.F14:
                //    break;
                //case Keys.F15:
                //    break;
                //case Keys.F16:
                //    break;
                //case Keys.F17:
                //    break;
                //case Keys.F18:
                //    break;
                //case Keys.F19:
                //    break;
                //case Keys.F20:
                //    break;
                //case Keys.F21:
                //    break;
                //case Keys.F22:
                //    break;
                //case Keys.F23:
                //    break;
                //case Keys.F24:
                //    break;
                //case Keys.NumPad0:
                //    break;
                //case Keys.NumPad1:
                //    break;
                //case Keys.NumPad2:
                //    break;
                //case Keys.NumPad3:
                //    break;
                //case Keys.NumPad4:
                //    break;
                //case Keys.NumPad5:
                //    break;
                //case Keys.NumPad6:
                //    break;
                //case Keys.NumPad7:
                //    break;
                //case Keys.NumPad8:
                //    break;
                //case Keys.NumPad9:
                //    break;
                //case Keys.Multiply:
                //    break;
                //case Keys.Add:
                //    break;
                //case Keys.Separator:
                //    break;
                //case Keys.Subtract:
                //    break;
                //case Keys.Minus:
                //    break;
                //case Keys.Decimal:
                //    break;
                //case Keys.Divide:
                //    break;
                //case Keys.D0:
                //    break;
                //case Keys.D1:
                //    break;
                //case Keys.D2:
                //    break;
                //case Keys.D3:
                //    break;
                //case Keys.D4:
                //    break;
                //case Keys.D5:
                //    break;
                //case Keys.D6:
                //    break;
                //case Keys.D7:
                //    break;
                //case Keys.D8:
                //    break;
                //case Keys.D9:
                //    break;
                //case Keys.A:
                //    break;
                //case Keys.B:
                //    break;
                //case Keys.C:
                //    break;
                //case Keys.D:
                //    break;
                //case Keys.E:
                //    break;
                //case Keys.F:
                //    break;
                //case Keys.G:
                //    break;
                //case Keys.H:
                //    break;
                //case Keys.I:
                //    break;
                //case Keys.J:
                //    break;
                //case Keys.K:
                //    break;
                //case Keys.L:
                //    break;
                //case Keys.M:
                //    break;
                //case Keys.N:
                //    break;
                //case Keys.O:
                //    break;
                //case Keys.P:
                //    break;
                //case Keys.Q:
                //    break;
                //case Keys.R:
                //    break;
                //case Keys.S:
                //    break;
                //case Keys.T:
                //    break;
                //case Keys.U:
                //    break;
                //case Keys.V:
                //    break;
                //case Keys.W:
                //    break;
                //case Keys.X:
                //    break;
                //case Keys.Y:
                //    break;
                //case Keys.Z:
                //    break;
                //case Keys.OemSemicolon:
                //    break;
                //case Keys.OemGrave:
                //    break;
                //case Keys.OemPlus:
                //    break;
                //case Keys.OemComma:
                //    break;
                //case Keys.OemMinus:
                //    break;
                //case Keys.OemPeriod:
                //    break;
                //case Keys.OemQuestion:
                //    break;
                //case Keys.OemTilde:
                //    break;
                //case Keys.OemOpenBrackets:
                //    break;
                //case Keys.OemPipe:
                //    break;
                //case Keys.OemCloseBrackets:
                //    break;
                //case Keys.OemQuotes:
                //    break;
                //case Keys.OemBackslash:
                //    break;
                //case Keys.OemClear:
                //    break;
                //default:
                //    break;
            }
        }
    }
}
