namespace Mallos.Input.Window
{
    using Veldrid.Sdl2;

    internal static class Sdl2Helper
    {
        public static MouseButtons Convert(this SDL_MouseButton button)
        {
            switch (button)
            {
                case SDL_MouseButton.Left:
                    return MouseButtons.Left;
                case SDL_MouseButton.Middle:
                    return MouseButtons.Middle;
                case SDL_MouseButton.Right:
                    return MouseButtons.Right;
                case SDL_MouseButton.X1:
                    return MouseButtons.XButton1;
                case SDL_MouseButton.X2:
                    return MouseButtons.XButton2;
                default:
                    return MouseButtons.Left;
            }
        }

        public static Keys Convert(this SDL_Keysym keysym)
        {
            switch (keysym.scancode)
            {
                case SDL_Scancode.SDL_SCANCODE_A:
                    return Keys.A;
                case SDL_Scancode.SDL_SCANCODE_B:
                    return Keys.B;
                case SDL_Scancode.SDL_SCANCODE_C:
                    return Keys.C;
                case SDL_Scancode.SDL_SCANCODE_D:
                    return Keys.D;
                case SDL_Scancode.SDL_SCANCODE_E:
                    return Keys.E;
                case SDL_Scancode.SDL_SCANCODE_F:
                    return Keys.F;
                case SDL_Scancode.SDL_SCANCODE_G:
                    return Keys.G;
                case SDL_Scancode.SDL_SCANCODE_H:
                    return Keys.H;
                case SDL_Scancode.SDL_SCANCODE_I:
                    return Keys.I;
                case SDL_Scancode.SDL_SCANCODE_J:
                    return Keys.J;
                case SDL_Scancode.SDL_SCANCODE_K:
                    return Keys.K;
                case SDL_Scancode.SDL_SCANCODE_L:
                    return Keys.L;
                case SDL_Scancode.SDL_SCANCODE_M:
                    return Keys.M;
                case SDL_Scancode.SDL_SCANCODE_N:
                    return Keys.N;
                case SDL_Scancode.SDL_SCANCODE_O:
                    return Keys.O;
                case SDL_Scancode.SDL_SCANCODE_P:
                    return Keys.P;
                case SDL_Scancode.SDL_SCANCODE_Q:
                    return Keys.Q;
                case SDL_Scancode.SDL_SCANCODE_R:
                    return Keys.R;
                case SDL_Scancode.SDL_SCANCODE_S:
                    return Keys.S;
                case SDL_Scancode.SDL_SCANCODE_T:
                    return Keys.T;
                case SDL_Scancode.SDL_SCANCODE_U:
                    return Keys.U;
                case SDL_Scancode.SDL_SCANCODE_V:
                    return Keys.V;
                case SDL_Scancode.SDL_SCANCODE_W:
                    return Keys.W;
                case SDL_Scancode.SDL_SCANCODE_X:
                    return Keys.X;
                case SDL_Scancode.SDL_SCANCODE_Y:
                    return Keys.Y;
                case SDL_Scancode.SDL_SCANCODE_Z:
                    return Keys.Z;
                case SDL_Scancode.SDL_SCANCODE_1:
                    return Keys.D1;
                case SDL_Scancode.SDL_SCANCODE_2:
                    return Keys.D2;
                case SDL_Scancode.SDL_SCANCODE_3:
                    return Keys.D3;
                case SDL_Scancode.SDL_SCANCODE_4:
                    return Keys.D4;
                case SDL_Scancode.SDL_SCANCODE_5:
                    return Keys.D5;
                case SDL_Scancode.SDL_SCANCODE_6:
                    return Keys.D6;
                case SDL_Scancode.SDL_SCANCODE_7:
                    return Keys.D7;
                case SDL_Scancode.SDL_SCANCODE_8:
                    return Keys.D8;
                case SDL_Scancode.SDL_SCANCODE_9:
                    return Keys.D9;
                case SDL_Scancode.SDL_SCANCODE_0:
                    return Keys.D0;
                case SDL_Scancode.SDL_SCANCODE_RETURN:
                    return Keys.Enter;
                case SDL_Scancode.SDL_SCANCODE_ESCAPE:
                    return Keys.Escape;
                case SDL_Scancode.SDL_SCANCODE_BACKSPACE:
                    return Keys.BackSpace;
                case SDL_Scancode.SDL_SCANCODE_TAB:
                    return Keys.Tab;
                case SDL_Scancode.SDL_SCANCODE_SPACE:
                    return Keys.Space;
                case SDL_Scancode.SDL_SCANCODE_MINUS:
                    return Keys.Minus;
                case SDL_Scancode.SDL_SCANCODE_EQUALS:
                    return Keys.OemPlus;
                case SDL_Scancode.SDL_SCANCODE_LEFTBRACKET:
                    return Keys.OemOpenBrackets;
                case SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET:
                    return Keys.OemCloseBrackets;
                case SDL_Scancode.SDL_SCANCODE_BACKSLASH:
                    return Keys.OemBackslash;
                case SDL_Scancode.SDL_SCANCODE_SEMICOLON:
                    return Keys.OemSemicolon;
                case SDL_Scancode.SDL_SCANCODE_APOSTROPHE:
                    return Keys.OemQuotes;
                case SDL_Scancode.SDL_SCANCODE_GRAVE:
                    return Keys.OemGrave;
                case SDL_Scancode.SDL_SCANCODE_COMMA:
                    return Keys.OemComma;
                case SDL_Scancode.SDL_SCANCODE_PERIOD:
                    return Keys.OemPeriod;
                case SDL_Scancode.SDL_SCANCODE_SLASH:
                    return Keys.Unknown;
                case SDL_Scancode.SDL_SCANCODE_CAPSLOCK:
                    return Keys.CapsLock;
                case SDL_Scancode.SDL_SCANCODE_F1:
                    return Keys.F1;
                case SDL_Scancode.SDL_SCANCODE_F2:
                    return Keys.F2;
                case SDL_Scancode.SDL_SCANCODE_F3:
                    return Keys.F3;
                case SDL_Scancode.SDL_SCANCODE_F4:
                    return Keys.F4;
                case SDL_Scancode.SDL_SCANCODE_F5:
                    return Keys.F5;
                case SDL_Scancode.SDL_SCANCODE_F6:
                    return Keys.F6;
                case SDL_Scancode.SDL_SCANCODE_F7:
                    return Keys.F7;
                case SDL_Scancode.SDL_SCANCODE_F8:
                    return Keys.F8;
                case SDL_Scancode.SDL_SCANCODE_F9:
                    return Keys.F9;
                case SDL_Scancode.SDL_SCANCODE_F10:
                    return Keys.F10;
                case SDL_Scancode.SDL_SCANCODE_F11:
                    return Keys.F11;
                case SDL_Scancode.SDL_SCANCODE_F12:
                    return Keys.F12;
                case SDL_Scancode.SDL_SCANCODE_PRINTSCREEN:
                    return Keys.PrintScreen;
                case SDL_Scancode.SDL_SCANCODE_SCROLLLOCK:
                    return Keys.ScrollLock;
                case SDL_Scancode.SDL_SCANCODE_PAUSE:
                    return Keys.Pause;
                case SDL_Scancode.SDL_SCANCODE_INSERT:
                    return Keys.Insert;
                case SDL_Scancode.SDL_SCANCODE_HOME:
                    return Keys.Home;
                case SDL_Scancode.SDL_SCANCODE_PAGEUP:
                    return Keys.PageUp;
                case SDL_Scancode.SDL_SCANCODE_DELETE:
                    return Keys.Delete;
                case SDL_Scancode.SDL_SCANCODE_END:
                    return Keys.End;
                case SDL_Scancode.SDL_SCANCODE_PAGEDOWN:
                    return Keys.PageDown;
                case SDL_Scancode.SDL_SCANCODE_RIGHT:
                    return Keys.Right;
                case SDL_Scancode.SDL_SCANCODE_LEFT:
                    return Keys.Left;
                case SDL_Scancode.SDL_SCANCODE_DOWN:
                    return Keys.Down;
                case SDL_Scancode.SDL_SCANCODE_UP:
                    return Keys.Up;
                case SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR:
                    return Keys.NumLock;
                case SDL_Scancode.SDL_SCANCODE_KP_DIVIDE:
                    return Keys.Divide;
                case SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY:
                    return Keys.Multiply;
                case SDL_Scancode.SDL_SCANCODE_KP_MINUS:
                    return Keys.Minus;
                case SDL_Scancode.SDL_SCANCODE_KP_PLUS:
                    return Keys.OemPlus;
                case SDL_Scancode.SDL_SCANCODE_KP_ENTER:
                    return Keys.Enter;
                case SDL_Scancode.SDL_SCANCODE_KP_1:
                    return Keys.NumPad1;
                case SDL_Scancode.SDL_SCANCODE_KP_2:
                    return Keys.NumPad2;
                case SDL_Scancode.SDL_SCANCODE_KP_3:
                    return Keys.NumPad3;
                case SDL_Scancode.SDL_SCANCODE_KP_4:
                    return Keys.NumPad4;
                case SDL_Scancode.SDL_SCANCODE_KP_5:
                    return Keys.NumPad5;
                case SDL_Scancode.SDL_SCANCODE_KP_6:
                    return Keys.NumPad6;
                case SDL_Scancode.SDL_SCANCODE_KP_7:
                    return Keys.NumPad7;
                case SDL_Scancode.SDL_SCANCODE_KP_8:
                    return Keys.NumPad8;
                case SDL_Scancode.SDL_SCANCODE_KP_9:
                    return Keys.NumPad9;
                case SDL_Scancode.SDL_SCANCODE_KP_0:
                    return Keys.NumPad0;
                case SDL_Scancode.SDL_SCANCODE_KP_PERIOD:
                    return Keys.OemPeriod;
                case SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH:
                    return Keys.OemBackslash;
                case SDL_Scancode.SDL_SCANCODE_KP_EQUALS:
                    return Keys.OemPlus;
                case SDL_Scancode.SDL_SCANCODE_F13:
                case SDL_Scancode.SDL_SCANCODE_F14:
                case SDL_Scancode.SDL_SCANCODE_F15:
                case SDL_Scancode.SDL_SCANCODE_F16:
                case SDL_Scancode.SDL_SCANCODE_F17:
                case SDL_Scancode.SDL_SCANCODE_F18:
                case SDL_Scancode.SDL_SCANCODE_F19:
                case SDL_Scancode.SDL_SCANCODE_F20:
                case SDL_Scancode.SDL_SCANCODE_F21:
                case SDL_Scancode.SDL_SCANCODE_F22:
                case SDL_Scancode.SDL_SCANCODE_F23:
                case SDL_Scancode.SDL_SCANCODE_F24:
                    return Keys.Unknown;
                case SDL_Scancode.SDL_SCANCODE_MENU:
                    return Keys.Menu;
                case SDL_Scancode.SDL_SCANCODE_LCTRL:
                    return Keys.LeftControl;
                case SDL_Scancode.SDL_SCANCODE_LSHIFT:
                    return Keys.LeftShift;
                case SDL_Scancode.SDL_SCANCODE_LALT:
                    return Keys.LeftAlt;
                case SDL_Scancode.SDL_SCANCODE_RCTRL:
                    return Keys.RightControl;
                case SDL_Scancode.SDL_SCANCODE_RSHIFT:
                    return Keys.RightShift;
                case SDL_Scancode.SDL_SCANCODE_RALT:
                    return Keys.RightAlt;
                default:
                    return Keys.Unknown;
            }
        }
    }
}
