name: Publish Nightly Docs

on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2.3.4
        
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: mallos/Mallos.Input
        TARGET_BRANCH: docs
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
